### ISSUE TITLE
Clarify expandAll intent

### ISSUE THREAD

**Issue by FredLoney** [pleerock/ng2-accordion#13]
The documentation reads as follows:

> [expandAll]="true|false" Indicates if all panels should be expanded by default. Default is false. When using this option closeOthers is explicitly set to true, because this option does not make sense when you can have only one opened panel at the same time.

The "this" referents are confusing. The documentation should perhaps read as follows:

> [expandAll]="true|false" Indicates if all panels should be expanded by default. Default is false. If expandAll is set to true, then the closeOthers option has no effect, since all panels are opened.

Furthermore, I find that the only way to have all groups opened is to:

1. Set accordion [expandAll]=true, *and*
2. Set each group [isOpened]=true.

I don't know if that behavior is the intent. If so, then the documentation should so indicate. If not, then there is a separate bug.

**Comment by pleerock** [comment]
> The "this" referents are confusing

I have updated readme. Feel free to create a PR if you'll see any other errors.

> Furthermore, I find that the only way to have all groups opened is to:

I know there is an issue with it if accordion is wrapped into ngif or something. I'll try to find a time to fix this bug

**Comment by FredLoney** [comment]
Great, thanks for the prompt response, Umed.
