### ISSUE TITLE
Error: Uncaught (in promise): No Directive annotation found on AccordionGroup - Angular 2 (latest build)

### ISSUE THREAD

**Issue by MrBananaGuard** [pleerock/ng2-accordion#2]
Here is a snippet of the implementation i am using on my type script file:

`import {ACCORDION_DIRECTIVES} from "ng2-accordion/index";

@Component({
    selector: 'work',
    templateUrl: '/app/workflow/templates/work.component.html',
    directives: [ACCORDION_DIRECTIVES]
})`

The Html:

` <accordion>
                <accordion-group >
                    Its all about me.
                </accordion-group>
                <accordion-group >
                    This is content of the contacts
                </accordion-group>
                <accordion-group >
                    Content of the Map
                </accordion-group>
                <accordion-group>
                    Its all about me.
                </accordion-group>
            </accordion>`

the importing in the system.config.js:

`   var map = {
        'app':                        'app', // 'dist',
        'rxjs':                       'node_modules/rxjs',
        'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
        '@angular':                   'node_modules/@angular',
        'ng2-accordion':              'node_modules/ng2-accordion'
    };
    // packages tells the System loader how to load when no filename and/or no extension
    var packages = {
        'app':                        { main: 'main.js',  defaultExtension: 'js' },
        'rxjs':                       { defaultExtension: 'js' },
        'angular2-in-memory-web-api': { defaultExtension: 'js' },
        'ng2-accordion':              { main: 'index.js', defaultExtension: 'js' }
    };`

**Comment by pleerock** [comment]
Do you have compiler errors? You import looks wrong. It should be `import {ACCORDION_DIRECTIVES} from "ng2-accordion";`, not `import {ACCORDION_DIRECTIVES} from "ng2-accordion/index";`

**Comment by MrBananaGuard** [comment]
Still getting errors: here is a snippet of my component.ts:

`
import {CORE_DIRECTIVES, FORM_DIRECTIVES} from "angular2/common";
import {ACCORDION_DIRECTIVES} from "ng2-accordion";


@Component({
    selector: 'work',
    templateUrl: '/app/workflow/templates/work.component.html',
    directives: [ACCORDION_DIRECTIVES, CORE_DIRECTIVES, FORM_DIRECTIVES]
})
`
here is the HTML:

`
  <accordion>
                <accordion-group heading="About me">
                    Its all about me.
                </accordion-group>
                <accordion-group heading="Contacts">
                    This is content of the contacts
                </accordion-group>
                <accordion-group heading="Map">
                    Content of the Map
                </accordion-group>
                <accordion-group>
                    <accordion-heading>
                        Custom heading.
                    </accordion-heading>
                    Its all about me.
                </accordion-group>
            </accordion>
`


Error:

> angular2.dev.js:23941 Error: Uncaught (in promise): No Directive annotation found on AccordionGroup
    at resolvePromise (angular2-polyfills.js:543)
    at angular2-polyfills.js:520
    at ZoneDelegate.invoke (angular2-polyfills.js:332)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (angular2.dev.js:2111)
    at ZoneDelegate.invoke (angular2-polyfills.js:331)
    at Zone.run (angular2-polyfills.js:227)
    at angular2-polyfills.js:576
    at ZoneDelegate.invokeTask (angular2-polyfills.js:365)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (angular2.dev.js:2103)
    at ZoneDelegate.invokeTask (angular2-polyfills.js:364)

> aseException {message: "No Directive annotation found on AccordionGroup", stack: "Error: No Directive annotation found on AccordionG…modules/angular2/bundles/angular2.dev.js:25195:37"}message: "No Directive annotation found on AccordionGroup"stack: "Error: No Directive annotation found on AccordionGroup↵    at new BaseException (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:7521:21)↵    at DirectiveResolver.resolve (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:6809:13)↵    at RuntimeMetadataResolver.getDirectiveMetadata (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:23157:47)↵    at http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:23227:22↵    at Array.map (native)↵    at RuntimeMetadataResolver.getViewDirectivesMetadata (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:23226:25)↵    at TemplateCompiler._compileNestedComponentRuntime (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:25211:63)↵    at http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:25196:26↵    at Array.forEach (native)↵    at http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:25195:37"__proto__: ErrorconsoleError @ angular2-polyfills.js:469drainMicroTaskQueue @ angular2-polyfills.js:498ZoneTask.invoke @ angular2-polyfills.js:434
angular2-polyfills.js:471 Error: Uncaught (in promise): No Directive annotation found on AccordionGroup(…)consoleError @ angular2-polyfills.js:471drainMicroTaskQueue @ angular2-polyfills.js:498ZoneTask.invoke @ angular2-polyfills.js:434

**Comment by MrBananaGuard** [comment]
Since i am on angualr 2 RC1 here is my systemjs.config.js to show you my imports:

`
(function(global) {
    // map tells the System loader where to look for things
    var map = {
        'app':                        'app', // 'dist',
        'rxjs':                       'node_modules/rxjs',
        'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
        '@angular':                   'node_modules/@angular',
        'ng2-accordion':              'node_modules/ng2-accordion'
    };
    // packages tells the System loader how to load when no filename and/or no extension
    var packages = {
        'app':                        { main: 'main.js',  defaultExtension: 'js' },
        'rxjs':                       { defaultExtension: 'js' },
        'angular2-in-memory-web-api': { defaultExtension: 'js' },
        'ng2-accordion': { main: "index.js", defaultExtension: 'js' }
    };
    var packageNames = [
        '@angular/common',
        '@angular/compiler',
        '@angular/core',
        '@angular/http',
        '@angular/platform-browser',
        '@angular/platform-browser-dynamic',
        '@angular/router',
        '@angular/router-deprecated',
        '@angular/testing',
        '@angular/upgrade'
    ];
    // add package entries for angular packages in the form '@angular/common': { main: 'index.js', defaultExtension: 'js' }
    packageNames.forEach(function(pkgName) {
        packages[pkgName] = { main: 'index.js', defaultExtension: 'js' };
    });
    var config = {
        map: map,
        packages: packages
    }
    System.config(config);
})(this);
`

**Comment by pleerock** [comment]
configuration looks correct. Im also using it on rc1, with pretty much the same configuration and have no issues. Check if you are using latest version on ng2-accordion. Check if you are doing everything right with angular. For example from your error log I see `angular2-polyfills.js`, but there is no more angular2-polyfills.js in rc1

**Comment by MrBananaGuard** [comment]
OK Removed the 

> angular2-polyfills.js
Here are my imported dependencies:

`
"dependencies": {
    "angular2": "2.0.0-beta.14",
    "angular2-in-memory-web-api": "0.0.7",

    "@angular/common":  "2.0.0-rc.1",
    "@angular/compiler":  "2.0.0-rc.1",
    "@angular/core":  "2.0.0-rc.1",
    "@angular/http":  "2.0.0-rc.1",
    "@angular/platform-browser":  "2.0.0-rc.1",
    "@angular/platform-browser-dynamic":  "2.0.0-rc.1",
    "@angular/router":  "2.0.0-rc.1",
    "@angular/router-deprecated":  "2.0.0-rc.1",
    "@angular/upgrade":  "2.0.0-rc.1",

    "es6-promise": "^3.0.2",
    "es6-shim": "^0.35.0",

    "reflect-metadata": "^0.1.3",

    "rxjs": "5.0.0-beta.6",

    "zone.js": "^0.6.12",

    "bootstrap": "^3.3.6",

    "systemjs": "0.19.27",


    "jquery": "^2.2.2",
    "mdi": "^1.5.54",

    "ng2-material": "^0.3.5",
    "ng2-translate": "^1.11.0",
    "ng2-bootstrap": "1.0.16",
    "ng2-accordion": "^0.0.2",
    "moment": "2.13.0"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.2.0",
    "typescript": "^1.8.10",
    "typings":"^0.8.1",
    "bootswatch":"^3.3.6",
    "bootstrap-sass":"^3.3.6"
  }
`

The script imported in index.html

`
<script src="node_modules/es6-shim/es6-shim.min.js"></script>
<script src="node_modules/zone.js/dist/zone.js"></script>
<script src="node_modules/reflect-metadata/Reflect.js"></script>
<script src="node_modules/systemjs/dist/system.src.js"></script>


<script src="node_modules/rxjs/bundles/Rx.js"></script>

<script src="node_modules/angular2/bundles/angular2.dev.js"></script>
<script async src="node_modules/angular2/bundles/router.dev.js"></script>
<script src="node_modules/angular2/bundles/http.js"></script>

<script src="node_modules/jquery/dist/jquery.min.js"></script>


<script src="systemjs.config.js"></script>
<script>

    System.import('app').catch(function(err){ console.error(err); });

    /* System.import('app/main/components/main')
     .then(null, console.error.bind(console));*/
</script>
![capture](https://cloud.githubusercontent.com/assets/18513849/15387659/8aacd99a-1dae-11e6-977a-49ffcd78f1ed.PNG)

`

**Comment by MrBananaGuard** [comment]
OK got it working, had to fully implement the RC1 upgrade... using the correct imports. and removing all old scripts in the index.html
