### ISSUE TITLE
Unable to select checkboxes for accordion without opening them; Angular2, Bootstrap3

### ISSUE THREAD

**Issue by VishalaBaligar** [pleerock/ng2-accordion#4]
Hi,

I implemented the ng2-accordion to create an accordion group. Now, I'm trying to add checkboxes to each accordion header so I can select the panel and delete it. However, adding a checkbox to the accordion header makes it part of the toggable string ie. I can select the checkbox but it also collapses or opens the panel as appropriate. I do not want this. Is there any way I can insert a checkbox in the accordion header without it becoming a part of the toggable string?

Further, I want to add some empty lines between each accordion heading and change the font size and padding size in the panels. Is there anyway to do this?

Any help would be appreciated.

Thank you,
Vishala

**Comment by pleerock** [comment]
Hello,

install the latest version **0.0.4** and use `<accordion-toggle>` inside your `<accordion-heading>`

```html
<accordion>
        <accordion-group heading="About me">
            Its all about me.
        </accordion-group>
        <accordion-group heading="Contacts">
            This is content of the contacts
        </accordion-group>
        <accordion-group heading="Map">
            Content of the Map
        </accordion-group>
        <accordion-group>
            <accordion-heading>
                <input type="checkbox"> <accordion-toggle>Custom clickable heading</accordion-toggle>
            </accordion-heading>
            Its all about me.
        </accordion-group>
    </accordion>
```

And don't forget to star a project ;)

**Comment by VishalaBaligar** [comment]
Hi,

Sorry if I wasn't clear. I do not want the accordion body to open when I click on the checkbox. I tried the above code, but when I select the checkbox the accordion body opens. I want to only select the checkbox and not have the accordion body open along with it.

Also, I was able to find only ng2-accordion version 0.0.3 here:
https://www.npmjs.com/package/ng2-accordion

Please let me know if version 0.0.4 is available for download elsewhere.

Thanks for your help,
Vishala

**Comment by pleerock** [comment]
I completely understood your issue and added support in 0.0.4. But looks like I forgot to release this version, sorry about that. Now I released it, please try it

**Comment by VishalaBaligar** [comment]
Thanks so much! I will try it out.

Could you also tell me if there is way of making the accordion heading responsive? I added media queries but the text displays outside the div panel on mobiles..

Thank you,
Best Regards,
Vishala Baligar

**Comment by VishalaBaligar** [comment]
Thanks so much! I will try it out. Is there any way of making the accordion panels responsive? I tried adding media queries to reduce thefont size for mobile screens but the text gets pushed out of the accordion header..

**Comment by pleerock** [comment]
ng2-accordion uses same classes as bootstrap's accordion, so if in bootstrap's accordion there is a responsive, it should work. However if you see that bootstrap's accordion's responsiveness differs from this component's  responsiveness, then try to take a look what classes are missing to make it responsive and let me know. Im not so good in css
