### ISSUE TITLE
Remove arrow parameter

### ISSUE THREAD

**Issue by ghetolay** [pleerock/ng2-accordion#6]
To be clear in fact it's not the arrow parameter that bothers me but the implementation of it : 

```
<div class="caret" [ngStyle]="{ borderTop: isOpened ? '0' : '4px dashed', borderBottom: isOpened ? '4px dashed' : '0' }">
</div>
```

It's not customizable on any point (dom placement, design...) and it seems to me it should be part of `<accordion-heading>`. It's totally a customisation of the heading. We could do it like this : 

```
<accordion-group #g1>
    <accordion-heading>
        <div class="caret" [ngStyle]="{ borderTop: g1.isOpened ? '0' : '4px dashed', borderBottom: g1.isOpened ? '4px dashed' : '0' }">
        </div>
    </accordion-heading>
    Content
</accordion-group>
```

Or even create an `<accordion-arrow>` to avoid repetition. Talking about repetition big difference here is that `showArrow` parameter  was at the `<accordion>` level while here we must do it for each `<accordion-group>`.

What do you think ?

**Comment by pleerock** [comment]
I want arrows to be enabled as simple as possible. Those arrows are pretty standard, so Im sure some of people will use them. So Im still for a flag that do it. What about customization, maybe we can do something like you suggested (`<accordion-arrow>`), but I dont think this is needed, because user already can disable arrows and create his own the way he wants in `accordion-header`. If he wants to reuse that arrows he will need extract it into separate component, or create a special class and reuse it

**Comment by ghetolay** [comment]
In fact you are right about it being standard. I actually need it but since I have a different design (chevron) I can't use it. 

- Why not use classes instead of the hardcoded style using borders ? We could set a class when it's open like it's done for content panel, this would had a little customization ability through css.  
- Also a bit unrelated but why not use a ngIf instead of setting the display based on the showArrow parameter ?

**Comment by pleerock** [comment]
> Why not use classes instead of the hardcoded style using borders ? We could set a class when it's open like it's done for content panel, this would had a little customization ability through css.

I just implemented arrows without too deep thinking on it. We can refactor it and make them classes instead.

> Also a bit unrelated but why not use a ngIf instead of setting the display based on the showArrow parameter ?

because ngIf does template rendering which is much more overload then simply showing/hiding it

**Comment by ghetolay** [comment]
> I just implemented arrows without too deep thinking on it. We can refactor it and make them classes instead.

We could just set ```dropup``` class at the parent level (```<h4>```) for it to work with bootstrap but this is [meant for dropdown menu](http://getbootstrap.com/components/#dropdowns) and in our case ```dropup``` at parent level is not very explicit. Maybe add 2 classes this ```dropup``` and one directly on the element like ```open``` or ```ìn``` (like for content).

> because ngIf does template rendering which is much more overload then simply showing/hiding it

I would agree if we were to show/hide it a lot but here it's a 'setup' parameter that will likely never change during the lifetime of the component. So ```ngIf``` will just be treated at initialisation then it's change detection will never trigger again.
Anyway this was just a wondering, we won't find a perfect solution and it's not important enough for debate/benchmark so let's not waste too much time on this. Just think about it and decide whatever you want.

I may open a new issue about ```ngIf``` at the content panel which is more important for me than this one because it can have a big subtree underneath.

**Comment by pleerock** [comment]
> We could just set dropup class at the parent level for it to work with bootstrap but this is meant for dropdown menu and in our case dropup at parent level is not very explicit. Maybe add 2 classes this dropup and one directly on the element like open or ìn (like for content).


> I may open a new issue about ngIf at the content panel which is more important for me than this one because it can have a big subtree underneath.

need to see these changes in action ;)

**Comment by ghetolay** [comment]
On [my animation branch](https://github.com/ghetolay/ng2-accordion/tree/animation) I use both the ```dropup``` class on accordion element and ```ngIf``` for content.

Since we are going that road I think we should use an ```ngIf``` for content because we can have a lot of content and each content may have components. So cutting of all those unnecessary elements from memory and change detection would make a difference.

**Comment by pleerock** [comment]
create a PR and lets see these changes
